name: Auto Approve PRs

on:
  pull_request_target:
    types:
    - opened
    branches:
    - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      ${{ github.actor == 'LanikSJ' }}
      ${{ github.actor == 'github-actions' }}
    steps:
    - uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4.0.0
      if: github.actor == 'LanikSJ'
    - uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4.0.0
      if: github.actor == 'dependabot[bot]'
    - uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4.0.0
      if: github.actor == 'github-actions'
